### ISSUE TITLE
Yul compile error

### ISSUE THREAD

**Issue by lazovicff** [privacy-scaling-explorations/snark-verifier#32]
Got this on AWS, but not locally:
```
Warning: Yul and its optimizer are still experimental. Please use the output with care.
<stdin>:4:39: Error: Expected ':' but got ')'
                function allocate(size) -> ptr {
                                      ^
<stdin>:4:39: Error: Expected keyword "data" or "object" or "}".
                function allocate(size) -> ptr {
                                      ^
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ec2-user/.cargo/git/checkouts/snark-verifier-972b60abf3a1213b/54452c7/snark-verifier/src/loader/evm/util.rs:123:19
```

`snark-verifier` version is pegged to `[54452c7](https://github.com/privacy-scaling-explorations/snark-verifier/commit/54452c71a5f9440a20a55ab4ea9b6d8cc4b5ea52)`

Anything else I can provide to debug this?

**Comment by lazovicff** [comment]
@jonathanpwang Thanks for the answer.
I see that you are the maintainer of https://github.com/axiom-crypto/snark-verifier/. Can you explain how it differs from this repo, and is it planned to be actively maintained?

**Comment by jonathanpwang** [comment]
The main difference is that in `halo2_loader` we use Axiom's `halo2-ecc` instead of `halo2wrong`. We also added a small SDK to help us use snark-verifier in production. We intend to actively maintain our repo while keeping it in sync of this one. We intend to upstream back all contributions that don't conflict (we have plans to upstream the SDK but just haven't gotten around to it yet).
