### ISSUE TITLE
EVM verifier of original proof failed but works for aggregated proof

### ISSUE THREAD

**Issue by DCMMC** [privacy-scaling-explorations/snark-verifier#36]
I made a range proof circuit and wanted to generate an EVM verifier for it but failed with out-of-gas when I tried to run the generated smart contract. But if I generated a aggregated proof from the original proof and generated the EVM verifier for the aggregated proof it works as expected. To reproduce this failure, please use `https://github.com/DCMMC/halo2-scaffold/tree/zk-range-proof` and run `cargo run --example range`. The code for generating EVM verifier for the original proof is `https://github.com/DCMMC/halo2-scaffold/blob/zk-range-proof/src/scaffold.rs#L323-L332`. And the failed verification is `https://github.com/DCMMC/halo2-scaffold/blob/zk-range-proof/src/scaffold.rs#L395-L397`. But the verification of the aggregated proof is success, see `https://github.com/DCMMC/halo2-scaffold/blob/zk-range-proof/src/scaffold.rs#L432-L433`. Is the EVM verifier generator only supports AggregationCircuit?

**Comment by jonathanpwang** [comment]
This is expected behavior - the code for the EVM verifier for the original proof probably exceeds the EVM contract bytecode size. The size of the EVM verifier increases with the number of columns in your circuit. Generally if you have >8 columns the bytecode will be too large. What the AggregationCircuit does is verify the original circuit into a circuit with <=6 columns, so the EVM bytecode is small enough to create.

**Comment by DCMMC** [comment]
Got it. Thanks you a lot!
